name: Deploy Website to GitHub Pages

on:
  push:
    branches: [ "main" ]

# GitHub Pages પર પબ્લિશ કરવા માટે ખાસ પરમિશન આપવી પડે
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    # GitHub Pages માટે સેટઅપ કરવું
    - name: Setup Pages
      uses: actions/configure-pages@v4

    # તમારી ફાઈલોને અપલોડ કરવી
    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: '.' # આખા ફોલ્ડરની ફાઈલો અપલોડ થશે

    # વેબસાઇટને લાઈવ (Deploy) કરવી
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
